server:
  port: 8081
spring:
  application:
    name: CmxAccounts
  datasource:
    url: jdbc:postgresql://localhost:5432/bank-sys?currentSchema=osu_cmx_accounts
    username: sys
    password: pass
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: db-changelog_main.xml
    enabled: true
    url: jdbc:postgresql://localhost:5432/bank-sys?currentSchema=osu_cmx_accounts
    user: sys
    password: pass
  jpa:
    hibernate:
      ddl-auto: none

springdoc:
  api-docs:
    resolve-schema-properties: true
    path: /api
  swagger-ui:
    path: /api/doc
    display-request-duration: true
    show-extensions: true
    show-common-extensions: true